config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  get 'oauths/secret_word', to: 'oauths#secret_word'
  post 'oauths/secret_word', to: 'oauths#secret_word'
  get 'login', to: 'oauths#login', as: :login
  delete 'logout', to: 'oauths#destroy', as: :logout

  resources :users, only: %i[index show edit update]
  resources :posts, only: %i[index show] do
    resources :comments, only: %i[create edit update destroy], shallow: true
  end

  namespace :admin do
    root to: 'base#top'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :posts, only: %i[index show new create edit update destroy] do
      collection { post :import }
    end

    resources :users, only: %i[index edit update destroy]
    resources :categories, only: %i[index new create edit update destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  def self.import(file, category_id)
    updatable_attributes = ["graduating_class", "name", "app_name", "contact", "app_url", "github_url", "usage_technology", "points_for_effort", "target_users", "pain_point", "remedy", "comment"]

    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      post = Post.create_or_find_by(id: row["id"]) do |p|
        p.attributes = row.to_hash.slice(*updatable_attributes)
        p.category_id = category_id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :provider, presence: true
  validates :uid, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/oauth.rb
class Oauth < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :graduating_class, presence: true
  validates :name, presence: true
  validates :app_name, presence: true
  validates :app_url, presence: true
  validates :github_url, presence: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :role, presence: true

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      redirect_to post_path(comment.post), notice: t('.success')
    else
      redirect_to posts_path(comment.post), alert: t('.fail')
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/controllers/oauths_controller.rb
require 'octokit'

class OauthsController < ApplicationController
  include Rails.application.routes.url_helpers

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    client = Octokit::Client.new(:access_token => ENV['GITHUB_PERSONAL_ACCESS_TOKEN'])
    if (@user = login_from(provider)) && client.organization_member?('runteq', @user.name )
      redirect_to posts_path,  notice: t('.success')
    else
      begin
        # 特定の組織にユーザーが所属しているかどうかを確認する
        @user = create_from(provider)
        if client.organization_member?('runteq', @user.name )
          reset_session
          auto_login(@user)
          redirect_to posts_path,  notice: t('.success')
        else
          redirect_to root_path, alert: t('.no_organization')
        end
      rescue
        redirect_to root_path, alert: t('.fail')
      end
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: t('.success')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @categories = Category.all
    @selected_category_id = params[:category_id]
    @posts = filtered_posts
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc) if @post
  end

  private

  def filtered_posts
    if @selected_category_id.present?
      Post.where(category_id: @selected_category_id)
    else
      last_category_id = @categories.last.try(:id)
      Post.where(category_id: last_category_id)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'top'
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def index
    @users = User.all
  end

  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to posts_path, notice: t('defaults.message.success')
    else
      flash.now[:warning] = t('defaults.message.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:nickname, :graduating_class)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Runfes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar bg-accent mb-8">
      <%= link_to t('defaults.app_admin'), admin_root_path, class:"btn btn-ghost normal-case text-xl" %>
    </div>
    <%= render 'shared/flash_message'%>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Runfes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Runfes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_category_filter.html.erb
<%= form_with url: posts_path, method: :get, local: true do |form| %>
  <div class="flex flex-row">
    <%= form.collection_select :category_id, Category.all.order(id: :asc), :id, :name, { prompt: t('defaults.message.select_default') }, selected: @selected_category_id, class: "select select-bordered select-primary select-sm w-40 max-w-xs" %>
    <%= form.submit t('defaults.filter'), class: "btn btn-primary ml-2 btn-sm" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-alert">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<div class="flex justify-center">
  <% flash.each do |type, message| %>
    <div class="py-1">
      <% if type == "notice" %>
        <div class="p-4 mb-4 text-sm font-medium text-blue-800 rounded-lg bg-blue-100">
          <%= message %>
        </div>
      <% elsif type == "alert" %>
        <div class="p-4 mb-4 text-sm font-medium text-red-800 rounded-lg bg-red-100">
          <span class="font-medium"><%= message %></span>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="navbar bg-neutral text-neutral-conten mb-4 sm:w-full">
  <div class="flex-1">
    <div><%= link_to t('defaults.app'), posts_path, class:"btn btn-ghost normal-case text-xl" %></div>
  </div>
  <div class="flex-none gap-2">
    <div class="form-control">
      <%= render 'shared/category_filter' %>
    </div>
  </div>
</div>