config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  get 'oauths/secret_word', to: 'oauths#secret_word'
  post 'oauths/secret_word', to: 'oauths#secret_word'
  get 'login', to: 'oauths#login', as: :login
  delete 'logout', to: 'oauths#destroy', as: :logout

  resources :users, only: %i[index show edit update]
  resources :posts, only: %i[index show] do
    resources :comments, only: %i[create edit update destroy], shallow: true
  end

  namespace :admin do
    root to: 'base#top'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :posts, only: %i[index show new create edit update destroy] do
      collection { post :import }
    end

    resources :users, only: %i[index edit update destroy]
    resources :categories, only: %i[index new create edit update destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  def self.import(file, category_id)
    updatable_attributes = ["graduating_class", "name", "app_name", "contact", "app_url", "github_url", "usage_technology", "points_for_effort", "target_users", "pain_point", "remedy", "comment"]

    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      post = Post.create_or_find_by(id: row["id"]) do |p|
        p.attributes = row.to_hash.slice(*updatable_attributes)
        p.category_id = category_id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :provider, presence: true
  validates :uid, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/oauth.rb
class Oauth < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :graduating_class, presence: true
  validates :name, presence: true
  validates :app_name, presence: true
  validates :app_url, presence: true
  validates :github_url, presence: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :role, presence: true

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.order(id: :asc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: t('defaults.message.success')
    else
      flash.now[:warning] = t('defaults.message.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :avatar, :graduating_class, :role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      redirect_to post_path(comment.post), notice: t('.success')
    else
      redirect_to posts_path(comment.post), alert: t('.fail')
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/controllers/oauths_controller.rb
require 'octokit'

class OauthsController < ApplicationController
  include Rails.application.routes.url_helpers

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    client = Octokit::Client.new(:access_token => ENV['GITHUB_PERSONAL_ACCESS_TOKEN'])
    if (@user = login_from(provider)) && client.organization_member?('runteq', @user.name )
      redirect_to posts_path,  notice: t('.success')
    else
      begin
        # 特定の組織にユーザーが所属しているかどうかを確認する
        @user = create_from(provider)
        if client.organization_member?('runteq', @user.name )
          reset_session
          auto_login(@user)
          redirect_to posts_path,  notice: t('.success')
        else
          redirect_to root_path, alert: t('.no_organization')
        end
      rescue
        redirect_to root_path, alert: t('.fail')
      end
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: t('.success')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @categories = Category.all
    @selected_category_id = params[:category_id]
    @posts = filtered_posts
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc) if @post
  end

  private

  def filtered_posts
    if @selected_category_id.present?
      Post.where(category_id: @selected_category_id)
    else
      last_category_id = @categories.last.try(:id)
      Post.where(category_id: last_category_id)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'top'
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def index
    @users = User.all
  end

  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to posts_path, notice: t('defaults.message.success')
    else
      flash.now[:warning] = t('defaults.message.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:nickname, :graduating_class)
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="ml-5">
  <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :nickname %>
      <%= f.text_field :nickname, class: 'input input-bordered w-full max-w-xs m-4' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'input input-bordered w-full max-w-xs m-4' %>
    </div>
    <div class="form-group">
      <%= f.label :graduating_class %>
      <%= f.text_field :graduating_class, class: 'input input-bordered w-full max-w-xs m-4' %>
    </div>
    <div class="form-group">
      <%= f.label :role %>
      <%= f.select :role, User.roles_i18n.invert, {}, class: 'input input-bordered w-full max-w-xs m-4' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="overflow-x-auto">
  <table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Nickame</th>
      <th>Email</th>
      <th>Graduating class</th>
      <th>Role</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th><%= user.id %></th>
          <td><%= user.name %></td>
          <td><%= user.nickname %></td>
          <td><%= user.email %></td>
          <td><%= user.graduating_class %></td>
          <td><%= user.role %></td>
          <td><%= link_to '📝', edit_admin_user_path(user) %></td>
          <td><%= button_to '🗑', admin_user_path(user), method: :delete,  data: { turbo_confirm: t('defaults.message.Are_you_sure') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path(@user), local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :graduating_class %>
    <%= f.text_field :graduating_class, class: 'input input-bordered w-full max-w-xs m-4' %>
  </div>

  <div class="form-group">
    <%= f.label :nicknamename %>
    <%= f.text_field :nickname, class: 'input input-bordered w-full max-w-xs m-4' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>